---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sample-app
spec:
  encryptedData:
    password: AgCDBprzg26izV3yBX0wWoWrwypnoTiuv4X4scVIfhx69AIfO6i9C54z23GIo2O/Y/X8GmmU5yRjAtVuHDUkacJJhGLslp5ReAjpyZVwSzPQJ2S5un/kFYOFHA2ZDnaE4NAe6ZhIT8A0L2/JuGiAt6mTz0A4A/zTS/sphFhPZIOqQIf9EB3PG7k9oPQ9bxxePJiZuUfvNofo62jnvnFdJ34oSn36m6ZjPHuzuHb5rhRPjiWq3X9KgFlPkQt+/FkmxDgHofoK+kpscJSOhhHIfwEqQLEEqN9FqDLAqNFhWhTeEfLKMwnwE5zZlJyLyywlCS5/HZOQOxWtYeuxQAiL/GciM7xziM9YfR7V/5w9KsW2nYDy30R47I9lenlEzdReeZh4Zk5VLc1LuyJ42lNzDjg36GAdzCC2f56Uy79fUSE32DDBWyi2Yr9RH5My8K9vdfONwL1rW4OF0L4Ly/Bsp9XSv8Ah3p+TAFLsrrONULNb3rZHEqNCEU0aMP1pgPKp8Wc2HH6/5ZRDjhwYPdnTott80rcWV840c9ow1OH+pNQk/tFFnjeaQQkKyeonJP0MfYQ011y+2CUOeait7IL5H94zqYjTRsFgYtLVaJzamLDH1nbZnj9EIAeGKsoaWgNkfiRhqQhkMuvOD6IhFRv3mc11waEQyUgl1ABEus3PLe/w42UFyGLqjSz49sduRSGn/QJBEl/YWguqLg==
  template:
    metadata:
      creationTimestamp: null
      name: sample-app
