apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-backend-app-service
  name: sample-backend-app-service
spec:
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8080
  selector:
    app: sample-backend-app
    tier: backend
