apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-frontend-app-service
  name: sample-frontend-app-service
spec:
  selector:
    app: sample-frontend-app
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer