apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test
  source:
    repoURL: https://github.com/RuBisCO28/k8s-sample-manifest.git
    targetRevision: main
    path: 09-cicd/sample-app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
